### ISSUE TITLE
Lagring og tagging av data

### ISSUE THREAD

**Issue by lepmik** [CINPLA/AnalysisPipeline#1]
Data kan lagres som HDF5 NEO objekter som inneholder spiketrains, LFP, tracking og/eller stimulus data. 

 - Hvor skal Data lagres?
  - En mappe med alle filer organisert med SQL eller mappestruktur
 - Hvordan skal man definere hvilke data som skal analyseres?
  - Tekstfil som peker på filnavn, SQL som leser tagger 
 - Tagging av filer eller mappestruktur
  - Dato, hjerneområde, rotte, eksperimentalist etc.

**Comment by lepmik** [comment]
spikesorta og så videre prossessert data skal bli lagret som sekundærdata i en mappe med filer fra alle eksperimenter.

**Comment by lepmik** [comment]
rådata skal bli kopiert som backup til sekundærfilområde. sekundærfiler skal linke til disse.

**Comment by dragly** [comment]
SQL brukes enten ikke i det hele tatt eller kun til indeksering av dataene som ligger i mappene fra før. Altså, for å lage et program som parser alle dataene i alle mappene og putter dette i en tabell. Men tabellen trengs kun hvis denne parseren blir treg når vi har mye data. Ellers kan det bare gjøres live i et GUI.
