### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by lepmik** [CINPLA/AnalysisPipeline#15]
skal all data skrives ut som xl ark? hvor skal figurer lagres, hva slags format skal de skrives som?

**Comment by lepmik** [comment]
lagre data i hjemmeområde i spesifisert format

**Comment by dragly** [comment]
All data about an experiment is to be stored in an experiment file (.exp.h5) that links to the raw data and adds attributes to this. See #22 for details.

Further analyses should either write into the experiment file (by tagging the data) or by copying the experiment folder and adding more data and figures to this new folder. When to do what depends on the amount of new data and how likely it is that adding it to the original file will conflict with other analyses.
