### ISSUE TITLE
Struktur av sekundærfil

### ISSUE THREAD

**Issue by lepmik** [CINPLA/AnalysisPipeline#22]
Mappestruktur:

År:
Måned:
dato_tid_Rotte:
dato_tid_Rotte.hdf5
Raw:
alle filer

Hard (Mandatory)
 - rotte, session, dato
 - rådata link

Medium (Optional, but standardisert)
 - Opto
  - peker på data
  - notes
 - Visuell
  - type
  - notes
 - Tracking
  - environment
  - size (if round - what dim?)
  - notes
 - Footshock
  - environment
  - size (if round - what dim?)
  - notes
 - Anatomi (en liste høyre, en venstre)
  - dybde av elektrode
  - hjerneområde 
   - Merk av hvilket område som er relevant

Soft (Optional, not standarized)
 - User data
  - rom (familiært, nytt)
  - eksperimentell tilstand (control, injected)
  - other information

**Comment by dragly** [comment]
List moved to a file defining the structure here:

https://github.com/CINPLA/AnalysisPipeline/blob/master/definition/experiment_definition.yml
